# Generated by Django 5.1.6 on 2025-04-14 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.CharField(choices=[('A', 'A Section'), ('B', 'B Section'), ('C', 'C Section')], max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('coordinator_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='pbkdf2_sha256$870000$TcAAms4OzLEZQChFE5dqov$kGOX/MepxmBAN0u66JHl32P2TLKQueH45dxdvYeljp4=', max_length=128)),
                ('user_type', models.CharField(default='coordinator', max_length=10)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='pbkdf2_sha256$870000$Edyu5vduTD7Y4knbbWVvj3$vRhWnw4m9r+OygMTNNyICZoRZepIveff0RChjkfxCb4=', max_length=128)),
                ('user_type', models.CharField(default='mentor', max_length=10)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradifyPortal.coordinator')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='pbkdf2_sha256$870000$uvKnSLoDJhSkOaurMXpFPy$0mV0PAsEAUIDAwBDooa+/NnXy4Rg0WH3w5bYhpgH8do=', max_length=128)),
                ('user_type', models.CharField(default='student', max_length=10)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradifyPortal.section')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='GradifyPortal.mentor')),
                ('sender_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GradifyPortal.mentor')),
                ('recipient_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='GradifyPortal.student')),
                ('sender_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GradifyPortal.student')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradifyPortal.mentor')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradifyPortal.section')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='GradifyPortal.team')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('document', models.FileField(upload_to='submissions/')),
                ('document_hash', models.CharField(blank=True, max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('mentor_approved', 'Mentor Approved'), ('mentor_rejected', 'Mentor Rejected'), ('coordinator_approved', 'Coordinator Approved')], default='submitted', max_length=20)),
                ('mentor_feedback', models.TextField(blank=True)),
                ('coordinator_feedback', models.TextField(blank=True)),
                ('mentor_signature', models.CharField(blank=True, max_length=256, null=True)),
                ('coordinator_signature', models.CharField(blank=True, max_length=256, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradifyPortal.student')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GradifyPortal.task')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradifyPortal.team')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradifyPortal.team'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField()),
                ('methodology', models.IntegerField()),
                ('presentation', models.IntegerField()),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.TextField(blank=True, null=True)),
                ('evaluated_by_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GradifyPortal.coordinator')),
                ('evaluated_by_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GradifyPortal.mentor')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradifyPortal.submission')),
            ],
            options={
                'unique_together': {('submission', 'evaluated_by_coordinator'), ('submission', 'evaluated_by_mentor')},
            },
        ),
    ]
