# Generated by Django 5.1.6 on 2025-04-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradifyPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$H17zELc9Kg5A7jDZwopWpo$uMiBBSxFEdZZVgOTXEUMB1oJ1+2/BHKKwZCOQvCqKYQ=', max_length=128),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='user_type',
            field=models.CharField(default='coordinator', max_length=15),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$ENHJHW2PW72rfpw3svM8fE$6gHwHrZjMlGljCv+LEwbi3NlGfsxeajPFG5OPk89vZg=', max_length=128),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='user_type',
            field=models.CharField(default='mentor', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$FONzawneKmZhBgQd8vjnXa$kLI4Nk5bI6BTa2JhOGjp/t2lWDn6rVCfbuDFWhy1txU=', max_length=128),
        ),
    ]
