# Generated by Django 5.1.6 on 2025-04-14 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradifyPortal', '0002_alter_coordinator_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='task',
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$is0K0wD2aGFRB4q7aLbOSp$cRZGigZHG/46/hTQ8DQN/5RSDMJ1FGjWR3dXkWuNoMw=', max_length=128),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='user_type',
            field=models.CharField(default='coordinator', max_length=10),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GradifyPortal.submission'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$ugy6h0ERMmVoETDgVhPW9a$Af6RXrUeyyK379RtghGFSJIcr/ksaFiQN27k2P36GxA=', max_length=128),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='user_type',
            field=models.CharField(default='mentor', max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.CharField(choices=[('A', 'A Section'), ('B', 'B Section'), ('C', 'C Section'), ('D', 'D Section'), ('E', 'E Section')], max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$duHGX9jKZNUlY531bFXoZr$WFYdOeXa0YzvmaLk7l5uhntR8RPSj24GMiisMMtz4bs=', max_length=128),
        ),
        migrations.AlterField(
            model_name='submission',
            name='coordinator_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='mentor_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('mentor_approved', 'Mentor Approved'), ('mentor_rejected', 'Mentor Rejected'), ('coordinator_approved', 'Coordinator Approved')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
