# Generated by Django 5.1.6 on 2025-04-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradifyPortal', '0003_remove_submission_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$OcbTOyMtfnB32l2VBKJGb5$eMtDiEjc5+5NfW6WmwFnWSlDT7nHIyM3r7Z5B98B+pw=', max_length=128),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='user_type',
            field=models.CharField(default='coordinator', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$eeZeDa8V90obe6kERXiJ6B$6A6Rd+uJPaIiKg+6kHeRmyRawoYy5Cas57j1ZXczvrk=', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$TInl9NhWBRSoWEg5ZoMWAF$/QpeTeqAl0TPxTCA/SbcC1mJ/iSN6Sq6RSo/GdtmQYQ=', max_length=128),
        ),
    ]
