# Generated by Django 5.1.6 on 2025-04-14 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradifyPortal', '0004_alter_coordinator_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$qpEjHyD01pBb4bwKNHd6eK$tH/3aM71A6LXBLXXBvszGWww6XLGuynRC/+mibw05/E=', max_length=128),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$7EBp8Ej3z85RdckOju2Hls$XJ0WEQsVA/+ZHsSko923cKlf/rjG5yX6FCPdLKwdh/I=', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$RabH9L4wNDE4BfBjAoxUGI$5dWqcUfwpF8i/P71RFvFJzXb1ezO2aBBn6CM/J7OO1g=', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GradifyPortal.team'),
        ),
    ]
