# Generated by Django 5.1.6 on 2025-04-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradifyPortal', '0005_alter_coordinator_password_alter_mentor_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$ZStZ1hOeleUVz1JJYOtaKc$CVYzl56jSQkCt5iTgLeNbLla9oNsdGTIqVvmoswQkjo=', max_length=128),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$xvEUzWdkoj65bML2k09PAa$qvcQ1sYgycVML8gAaenVrLgCgOuEqM0HDcjZPgZz28U=', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$4Gu30AVDcTsMWakE9h2D5L$w2r+x21+Xt5sCQSsLTuaUQPd2NkaiAl9lZNkeS9HYAg=', max_length=128),
        ),
    ]
