# Generated by Django 5.1.6 on 2025-04-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradifyPortal', '0006_alter_coordinator_password_alter_mentor_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$B3hQq5Wn280SFwKlyPgRZk$79AHcTic3/8ftp9SNY5QmaxeVEQS7NgoGX9NfUj0Y30=', max_length=128),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$s4bi1LB1BoNxSHCymaz3s7$muCbWWE0FYK9jmDxXDnUzGZFkVTtLjF0KnrSwo94PeY=', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$BONIXn9Zz20rBMLM0pev17$KN0KLEEKqAVKX1SFiPUKSajl8GRbXg8nhgrQfHGzcbk=', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('submission', 'evaluated_by_coordinator')},
        ),
    ]
